# Generated by Django 3.1.3 on 2020-11-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsive_form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
